import { useMemo } from "react";
import { CreditCard, Wallet, Landmark, Smartphone } from "lucide-react";
import { Button, Card, Input } from "../../components/ui";
import type { BillingItem } from "./ProductTable";
import { calculateBill } from "../../features/billing/utils/billingCalculator";
type PaymentPanelProps = { items: BillingItem[]; paymentMethod: string; setPaymentMethod: React.Dispatch<React.SetStateAction<string>>; received: number; setReceived: React.Dispatch<React.SetStateAction<number>>; onSave: () => void };
export default function PaymentPanel({ items, paymentMethod, setPaymentMethod, received, setReceived, onSave }: PaymentPanelProps) {
  const summary = useMemo(() => calculateBill(items, "amount", 0, "included"), [items]);
  const outstanding = Math.max(0, summary.grandTotal - received); const change = received > summary.grandTotal ? received - summary.grandTotal : 0;
  return <Card className="billing-card billing-payment"><h2>Payment</h2><div className="billing-payment__body"><Input label="Amount Received" type="number" value={received} onChange={(e) => setReceived(Number(e.target.value))} placeholder="0" /><div><span className="kv-field__label">Payment Method</span><div className="billing-payment-methods"><StatusButton active={paymentMethod === "Cash"} icon={<Wallet size={18} />} text="Cash" onClick={() => setPaymentMethod("Cash")} /><StatusButton active={paymentMethod === "UPI"} icon={<Smartphone size={18} />} text="UPI" onClick={() => setPaymentMethod("UPI")} /><StatusButton active={paymentMethod === "Card"} icon={<CreditCard size={18} />} text="Card" onClick={() => setPaymentMethod("Card")} /><StatusButton active={paymentMethod === "Bank"} icon={<Landmark size={18} />} text="Bank" onClick={() => setPaymentMethod("Bank")} /></div></div><hr /><Row label="Bill Amount" value={`₹${summary.grandTotal.toFixed(2)}`} /><Row label="Received" value={`₹${received.toFixed(2)}`} /><Row label="Outstanding" value={`₹${outstanding.toFixed(2)}`} />{change > 0 && <Row label="Change" value={`₹${change.toFixed(2)}`} />}<Row label="Status" value={outstanding === 0 ? "Paid" : "Partial Payment"} /><Button size="lg" fullWidth onClick={onSave} disabled={items.length === 0}>Save Bill</Button></div></Card>;
}
function Row({ label, value }: { label: string; value: string }) { return <div className="billing-summary-row"><span>{label}</span><strong>{value}</strong></div>; }
function StatusButton({ icon, text, active, onClick }: { icon: React.ReactNode; text: string; active: boolean; onClick: () => void }) { return <Button variant={active ? "primary" : "secondary"} className="billing-payment-method" onClick={onClick}>{icon}{text}</Button>; }
