import { Badge, Modal, Table } from "../../../components/ui";
import type { Purchase } from "../../../types/purchase";

type PurchaseDetailsProps = { purchase: Purchase | null; onClose: () => void };
const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", minimumFractionDigits: 2 });

export default function PurchaseDetails({ purchase, onClose }: PurchaseDetailsProps) {
  return <Modal open={Boolean(purchase)} onClose={onClose} title={purchase ? purchase.purchaseNumber : "Purchase details"} description="Posted purchase invoice and received-stock audit." width="980px">{purchase && <div className="purchase-details"><div className="purchase-details__summary"><div><span>Supplier</span><strong>{purchase.supplierName}</strong></div><div><span>Supplier invoice</span><strong>{purchase.invoiceNumber || "—"}</strong></div><div><span>Purchase date</span><strong>{purchase.purchaseDate}</strong></div><div><span>Status</span><Badge variant="success">Posted</Badge></div></div><Table compact><thead><tr><th>Item Code</th><th>Product</th><th className="purchase-details__numeric">Qty</th><th className="purchase-details__numeric">Price</th><th className="purchase-details__numeric">GST</th><th className="purchase-details__numeric">Discount</th><th className="purchase-details__numeric">Amount</th></tr></thead><tbody>{purchase.items?.map((item) => <tr key={item.id}><td>{item.itemCode}</td><td>{item.productName}</td><td className="purchase-details__numeric">{item.quantity}</td><td className="purchase-details__numeric">{currency.format(item.purchasePrice)}</td><td className="purchase-details__numeric">{item.gstRate}%</td><td className="purchase-details__numeric">{currency.format(item.discount)}</td><td className="purchase-details__numeric">{currency.format(item.total)}</td></tr>)}</tbody></Table><div className="purchase-details__totals"><span>Subtotal <strong>{currency.format(purchase.subtotal)}</strong></span><span>GST <strong>{currency.format(purchase.gstAmount)}</strong></span><span>Paid <strong>{currency.format(purchase.paidAmount)}</strong></span><span>Outstanding <strong>{currency.format(purchase.balanceAmount)}</strong></span><b>Total {currency.format(purchase.totalAmount)}</b></div>{purchase.remarks && <p className="purchase-details__remarks"><strong>Remarks:</strong> {purchase.remarks}</p>}</div>}</Modal>;
}
