import { useEffect, useMemo, useState } from "react";
import { ClipboardList, Plus, RefreshCw } from "lucide-react";
import toast from "react-hot-toast";
import { Badge, Button, Card, DataUnavailable, Input, Modal, PageHeader, Table } from "../../../components/ui";
import type { Customer } from "../../../types/customer";
import type { OpticalJob, OpticalJobDashboard, OpticalJobStatus, RepairJob, RepairJobStatus } from "../../../types/optical";

type View = "PRESCRIPTION" | "REPAIR";
type RepairDetail = RepairJob & { timeline: Array<{ id: number; eventType: string; description: string; notes?: string | null; createdAt: string }> };
const prescriptionStatuses: OpticalJobStatus[] = ["NEW", "WAITING_FOR_LENS", "READY_FOR_DISPATCH"];
const repairStatuses: RepairJobStatus[] = ["NEW", "IN_PROGRESS", "READY", "DELIVERED"];

const label = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());
const date = (value?: string | null) => value ? new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) : "-";
const dateBucket = (value: string) => {
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const yesterday = new Date(today); yesterday.setDate(today.getDate() - 1);
  const created = new Date(value); created.setHours(0, 0, 0, 0);
  if (created.getTime() === today.getTime()) return "Today";
  if (created.getTime() === yesterday.getTime()) return "Yesterday";
  return "Older";
};
const statusBadge = (status: string) => status === "READY_FOR_DISPATCH" || status === "READY" || status === "DELIVERED" ? "success" as const : status === "WAITING_FOR_LENS" || status === "IN_PROGRESS" ? "warning" as const : "neutral" as const;

function RepairModal({ customers, onClose, onSaved }: { customers: Customer[]; onClose: () => void; onSaved: () => void }) {
  const [customerId, setCustomerId] = useState(""); const [itemReceived, setItemReceived] = useState(""); const [complaint, setComplaint] = useState(""); const [charges, setCharges] = useState("0");
  const save = async () => { try { await window.optical.createRepairJob({ customerId: Number(customerId), itemReceived, complaint, charges: Number(charges) }); toast.success("Repair job created."); onSaved(); onClose(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to create repair job."); } };
  return <Modal open onClose={onClose} title="New repair job" description="Repair work is independent from invoices and prescription jobs." footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={!customerId || !itemReceived.trim() || !complaint.trim()} onClick={() => void save()}>Create repair job</Button></>}>
    <div className="optical-job-detail__controls"><label className="kv-field"><span className="kv-field__label">Customer</span><select value={customerId} onChange={(event) => setCustomerId(event.target.value)}><option value="">Select customer</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name} · {customer.mobile}</option>)}</select></label><Input label="Item received" value={itemReceived} onChange={(event) => setItemReceived(event.target.value)} /><Input label="Complaint" value={complaint} onChange={(event) => setComplaint(event.target.value)} /><Input label="Charges" type="number" min="0" value={charges} onChange={(event) => setCharges(event.target.value)} /></div>
  </Modal>;
}

function RepairDetailModal({ job, onClose, onUpdated }: { job: RepairDetail | null; onClose: () => void; onUpdated: () => void }) {
  const [notes, setNotes] = useState("");
  const next = job ? ({ NEW: "IN_PROGRESS", IN_PROGRESS: "READY", READY: "DELIVERED" } as Partial<Record<RepairJobStatus, RepairJobStatus>>)[job.status] : undefined;
  const update = async () => { if (!job || !next) return; try { await window.optical.updateRepairJob(job.id, { status: next, notes }); toast.success("Repair job updated."); onUpdated(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update repair job."); } };
  return <Modal open={Boolean(job)} onClose={onClose} title={job ? `${job.jobNumber} · ${job.customerName}` : "Repair job"} footer={<Button variant="secondary" onClick={onClose}>Close</Button>}>
    {job ? <div className="optical-job-detail"><div className="optical-job-detail__summary"><div><span>Status</span><Badge variant={statusBadge(job.status)}>{label(job.status)}</Badge></div><div><span>Item received</span><strong>{job.itemReceived}</strong></div><div><span>Charges</span><strong>₹{job.charges}</strong></div></div><Card><p><strong>Complaint:</strong> {job.complaint}</p>{next ? <><Input label="Update note" value={notes} onChange={(event) => setNotes(event.target.value)} /><Button onClick={() => void update()}>Mark {label(next)}</Button></> : null}</Card><section className="optical-job-detail__timeline"><h3>Timeline</h3><ol>{job.timeline.map((event) => <li key={event.id}><div><strong>{label(event.eventType)}</strong><p>{event.description}</p>{event.notes ? <small>{event.notes}</small> : null}</div><time>{date(event.createdAt)}</time></li>)}</ol></section></div> : null}
  </Modal>;
}

export default function OpticalJobsPage() {
  const [view, setView] = useState<View>("PRESCRIPTION"); const [jobs, setJobs] = useState<OpticalJob[]>([]); const [repairs, setRepairs] = useState<RepairJob[]>([]); const [dashboard, setDashboard] = useState<OpticalJobDashboard | null>(null); const [customers, setCustomers] = useState<Customer[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const [showCreate, setShowCreate] = useState(false); const [detail, setDetail] = useState<RepairDetail | null>(null);
  const load = async () => { try { const [summary, prescription, repair, customerList] = await Promise.all([window.optical.getDashboard(), window.optical.getJobs({ search, status: view === "PRESCRIPTION" ? status as OpticalJobStatus | "ALL" : "ALL", pageSize: 100 }), window.optical.getRepairJobs(search), window.customer.getAll()]); setDashboard(summary); setJobs(prescription.items); setRepairs(repair.filter((job) => status === "ALL" || job.status === status)); setCustomers(customerList); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load optical jobs."); } };
  useEffect(() => { const timeout = window.setTimeout(() => void load(), 150); return () => window.clearTimeout(timeout); }, [search, status, view]);
  const displayed = view === "PRESCRIPTION" ? jobs : repairs;
  const groups = useMemo(() => (["Today", "Yesterday", "Older"] as const).map((group) => [group, displayed.filter((job) => dateBucket(job.createdAt) === group)] as const).filter(([, items]) => items.length), [displayed]);
  const setDashboardFilter = (nextView: View, nextStatus: string) => { setView(nextView); setStatus(nextStatus); };
  const openRepair = async (id: number) => { try { setDetail(await window.optical.getRepairJob(id) as RepairDetail); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load repair job."); } };
  const advancePrescription = async (job: OpticalJob) => { const next = job.status === "NEW" ? "WAITING_FOR_LENS" : job.status === "WAITING_FOR_LENS" ? "READY_FOR_DISPATCH" : undefined; if (!next) return; try { await window.optical.updateJob(job.id, { status: next }); toast.success(`Job marked ${label(next)}.`); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update job."); } };
  return <section className="optical-page"><PageHeader eyebrow="Workflow #6" title="Optical Jobs" subtitle="Prescription fulfilment and repair work are separate workflows." action={<div className="optical-job-detail__buttons"><Button variant="secondary" onClick={() => void load()}><RefreshCw size={16} /> Refresh</Button>{view === "REPAIR" ? <Button onClick={() => setShowCreate(true)}><Plus size={16} /> New repair job</Button> : null}</div>} />
    <div className="optical-job-detail__summary">{[["Incomplete prescription jobs", dashboard?.incompletePrescriptionJobs ?? 0, "PRESCRIPTION", "ALL"], ["Incomplete repair jobs", dashboard?.incompleteRepairJobs ?? 0, "REPAIR", "ALL"], ["Waiting for lens dispatch", dashboard?.waitingForLens ?? 0, "PRESCRIPTION", "WAITING_FOR_LENS"], ["Waiting at lab", dashboard?.waitingAtLab ?? 0, "PRESCRIPTION", "LAB_PENDING"], ["Ready for delivery", dashboard?.readyForDelivery ?? 0, "REPAIR", "READY"]].map(([title, count, nextView, nextStatus]) => <button key={title as string} type="button" onClick={() => setDashboardFilter(nextView as View, nextStatus as string)}><span>{title as string}</span><strong>{count as number}</strong></button>)}</div>
    <Card className="optical-jobs__toolbar"><div className="optical-job-detail__buttons"><Button variant={view === "PRESCRIPTION" ? "primary" : "secondary"} onClick={() => { setView("PRESCRIPTION"); setStatus("ALL"); }}>Prescription jobs</Button><Button variant={view === "REPAIR" ? "primary" : "secondary"} onClick={() => { setView("REPAIR"); setStatus("ALL"); }}>Repair jobs</Button></div><Input label="Search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder={view === "PRESCRIPTION" ? "Job, customer, invoice, frame or lens" : "Job, customer, item or complaint"} /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option>{(view === "PRESCRIPTION" ? prescriptionStatuses : repairStatuses).map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></Card>
    {groups.length ? groups.map(([group, items]) => <section key={group}><h3>{group}</h3><Card className="optical-page__queue"><Table><thead><tr><th>Job number</th><th>Customer</th>{view === "PRESCRIPTION" ? <><th>Invoice</th><th>Frame</th><th>Lens</th><th>Expected delivery</th></> : <><th>Item received</th><th>Complaint</th><th>Charges</th></>}<th>Status</th><th>Created</th><th /></tr></thead><tbody>{items.map((item) => { if (view === "PRESCRIPTION") { const job = item as OpticalJob; const next = job.status === "NEW" ? "WAITING_FOR_LENS" : job.status === "WAITING_FOR_LENS" ? "READY_FOR_DISPATCH" : null; return <tr key={job.id}><td>{job.jobNumber}</td><td>{job.customerName}</td><td>{job.orderNumber ?? "-"}</td><td>{job.frameDescription ?? "-"}</td><td>{[job.lensBrand, job.lensSeries].filter(Boolean).join(" ") || "-"}</td><td>{date(job.expectedDeliveryDate)}</td><td><Badge variant={statusBadge(job.status)}>{label(job.status)}</Badge></td><td>{date(job.createdAt)}</td><td>{next ? <Button size="sm" variant="ghost" onClick={() => void advancePrescription(job)}>Mark {label(next)}</Button> : null}</td></tr>; } const job = item as RepairJob; return <tr key={job.id}><td>{job.jobNumber}</td><td>{job.customerName}</td><td>{job.itemReceived}</td><td>{job.complaint}</td><td>₹{job.charges}</td><td><Badge variant={statusBadge(job.status)}>{label(job.status)}</Badge></td><td>{date(job.createdAt)}</td><td><Button size="sm" variant="ghost" onClick={() => void openRepair(job.id)}>Open</Button></td></tr>; })}</tbody></Table></Card></section>) : <DataUnavailable title={view === "PRESCRIPTION" ? "No prescription jobs" : "No repair jobs"} description={view === "PRESCRIPTION" ? "Prescription invoices create jobs automatically." : "Create a repair job to begin independent service work."} icon={<ClipboardList size={22} />} />}
    {showCreate ? <RepairModal customers={customers} onClose={() => setShowCreate(false)} onSaved={() => void load()} /> : null}<RepairDetailModal job={detail} onClose={() => setDetail(null)} onUpdated={() => { if (detail) void openRepair(detail.id); void load(); }} />
  </section>;
}
